<?php

namespace PIDEV\VoyageBundle\Repository;

/**
 * ReserverVoyageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReserverVoyageRepository extends \Doctrine\ORM\EntityRepository
{

    public function findDQLreservationParametre($idvoyage){

        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();
        $query = $qb->delete('PIDEVVoyageBundle:ReserverVoyage', 'buss')
            ->where('buss.id_voyage = :idVoyage')
            ->setParameter('idVoyage',$idvoyage )
            ->getQuery();

        $query->execute();



    }
}
