<?php

namespace PIDEV\PrestationBundle\Repository;

/**
 * CommentaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaireRepository extends \Doctrine\ORM\EntityRepository
{
    public function findbyprestation($idp)
    {
        $query=$this->getEntityManager()
            ->createQuery("Select c from PIDEVPrestationBundle:Commentaire c where IDENTITY(c.id_prestation) like :id")
            ->setParameter('id','%'.$idp.'%');
        return $query->getResult();
    }
    public function findsignales()
    {
        $query=$this->getEntityManager()
            ->createQuery("Select c from PIDEVPrestationBundle:Commentaire c where c.nbr_signalisation > 0");
        return $query->getResult();
    }
    public function findbyidprest($idp)
    {
        $query=$this->getEntityManager()
            ->createQuery("Select c.id_commentaire, IDENTITY(c.id_prestation), c.id_user.id_user,
c.contenu from PIDEVPrestationBundle:CommentairePrestation c where IDENTITY(c.id_prestation) like :id")
            ->setParameter('id','%'.$idp.'%');
        return $query->getResult();
    }

}
