<?php

namespace PIDEV\PrestationBundle\Repository;

/**
 * DiplomeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiplomeRepository extends \Doctrine\ORM\EntityRepository
{
    public function findbyid($id)
    {
        $query=$this->getEntityManager()
            ->createQuery("Select d from PIDEVPrestationBundle:Diplome d where d.id_diplome like :id")
            ->setParameter('id','%'.$id.'%');
        return $query->getResult();
    }
    public function findbyproperties($categorie, $type, $annee)
    {
        $parameters = array('cat' => '%'.$categorie.'%',
                            'type' => '%'.$type.'%',
                            'annee' => '%'.$annee.'%');
        $query=$this->getEntityManager()
            ->createQuery("Select d from PIDEVPrestationBundle:Diplome d
                          where d.categoriediplome like :cat and d.type like :type and d.dateObtention like :annee")
            ->setParameters($parameters);
        return $query->getResult();
    }
    public function findallcategoriesdiplome()
    {
        $query=$this->getEntityManager()
            ->createQuery("Select DISTINCT(d.categoriediplome) AS categorie from PIDEVPrestationBundle:Diplome d
 GROUP BY d.categoriediplome");
        return $query->getResult();
    }
    public function findalletabdispo()
    {
        $query=$this->getEntityManager()
            ->createQuery("Select DISTINCT(d.etablissement) AS etablissement from PIDEVPrestationBundle:Diplome d
 GROUP BY d.etablissement");
        return $query->getResult();
    }
}
