# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
            FOS\UserBundle\Model\UserInterface: plaintext
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                success_handler: redirect.after.login


            logout:
                target: /login
            anonymous:    true
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~


    role_hierarchy:
        ROLE_CLIENT:       ROLE_USER
        ROLE_AGENT:       ROLE_ADMIN

    access_control:
        - { path: ^/recommendation/allrec, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/recommendation/toprec, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/VoyageA/AfficherAllVoyagesM, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/VoyageA/ReserverVoyageMobile, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/VoyageA/MesReservationsMobile, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/VoyageA/AnnulerReservationMobile, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/VoyageA/AfficheReservationDetailMobile, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/VoyageA/SupprimerVoyageMobile, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/VoyageA/findOne, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/home, role: ROLE_CLIENT }
        - { path: ^/layout, role: ROLE_AGENT }
        - { path: ^/recommendation, role: ROLE_CLIENT }
        - { path: ^/recommendation, role: ROLE_AGENT }
        - { path: ^/Voyage, role: ROLE_CLIENT  }
        - { path: ^/event, role: IS_AUTHENTICATED_ANONYMOUSLY }



