pidev_user_homepage:
    path:     /
    defaults: { _controller: PIDEVUserBundle:Default:index }
login1:
    path:     /login1/{username}/{password}
    defaults: { _controller: PIDEVUserBundle:Default:login }
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
