<?php

namespace PIDEV\ProduitBundle\Repository;

/**
 * MenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeRepository extends \Doctrine\ORM\EntityRepository
{
    public function findbyIdProduit($id_produit){
        $query=$this->getEntityManager()->createQuery("
        select c from PIDEVProduitBundle:CommandeProd c 
        WHERE c.id_produit LIKE :s ")->setParameter('s','%'.$id_produit.'%');
        return $query->getResult();

    }}
