<?php

namespace PIDEV\ProduitBundle\Repository;

/**
 * PanierProdRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PanierProdRepository extends \Doctrine\ORM\EntityRepository
{
}
