<?php

namespace PIDEV\ProduitBundle\Repository;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends \Doctrine\ORM\EntityRepository
{
    public function findId($id_produit){
        $query=$this->getEntityManager()->createQuery("
        select v from PIDEVProduitBundle:Produit v 
        WHERE v.id_produit LIKE :s ")->setParameter('s','%'.$id_produit.'%');
        return $query->getResult();

    }
    public function findnom($nom_produit){
        $query=$this->getEntityManager()->createQuery("
        select v from PIDEVProduitBundle:Produit p
        WHERE p.id_produit LIKE :s ")->setParameter('s','%'.$nom_produit.'%');
        return $query->getResult();

    }


    function recherche($valeur){
        $query = ProduitRepository::createQueryBuilder('r')
            ->where('UPPER(r.nom_produit) LIKE UPPER(:valeur)')
            ->orWhere('UPPER(r.description) LIKE UPPER(:valeur)')
            ->orWhere('UPPER(r.categorie_produit) LIKE UPPER(:valeur)')


            ->setParameter('valeur','%'.$valeur.'%')
            ->getQuery();

        return $query->getResult();
    }

    public function NbrAime()
    {
        $query=$this->getEntityManager()->createQuery("
        select SUM (p.stock_produit) from PIDEVProduitBundle:Produit p
           GROUP BY p.categorie_produit");
        return $query->getResult();
    }



}
